[env]
TERM		= "xterm-256color"

[window]
dimensions	= { columns = 120, lines = 32 }
padding		= { x = 5, y = 5 }
decorations	= "none"
opacity		= 0.8
blur		= true

[scrolling]
history = 65535

[font]
normal		= { family = "ComicShannsMono Nerd Font", style = "Regular" }
bold		= { family = "ComicShannsMono Nerd Font", style = "Bold" }
italic		= { family = "ComicShannsMono Nerd Font", style = "Italic" }
bold_italic	= { family = "ComicShannsMono Nerd Font", style = "Bold Italic"}
size		= 10.5
offset		= { x = 0, y = 0 }
glyph_offset	= { x = 0, y = 0 }

[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"
dim_foreground = "#7f849c"
bright_foreground = "#cdd6f4"

[colors.cursor]
text = "#1e1e2e"
cursor = "#f5e0dc"

[colors.vi_mode_cursor]
text = "#1e1e2e"
cursor = "#b4befe"

[colors.search.matches]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.search.focused_match]
foreground = "#1e1e2e"
background = "#a6e3a1"

[colors.footer_bar]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.hints.start]
foreground = "#1e1e2e"
background = "#f9e2af"

[colors.hints.end]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.selection]
text = "#1e1e2e"
background = "#f5e0dc"

[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"

[colors.dim]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[[colors.indexed_colors]]
index = 16
color = "#fab387"

[[colors.indexed_colors]]
index = 17
color = "#f5e0dc"

[bell]
animation	= "EaseOutExpo"
duration	= 0
color		= '#73B1F4'
#command		= { program = "notify-send", args = ["alacritty", "bell"] }

[mouse]
hide_when_typing	= false
bindings	= [
	{ mouse = "Right", action = "Copy" },
	{ mouse = "Middle", action = "Paste" }
]

[cursor]
blink_interval	= 500
blink_timeout	= 0

[cursor.style]
shape		= "Block"
blinking	= "Always"

[keyboard]
bindings = [
	{ key = 'V', mods = "Command", action = "Paste" },
	{ key = 'C', mods = "Command", action = "Copy" }
]
